# Generated by Django 2.2.5 on 2019-09-15 11:04

from django.db import migrations, models
import exchange_watch.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', exchange_watch.models.CurrencyField(max_length=32)),
                ('secondary', exchange_watch.models.CurrencyField(max_length=32)),
                ('rate', models.FloatField()),
                ('last_update_date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('primary', 'secondary'), name='db_exchange_rate_primary_secondary_unique'),
        ),
        migrations.AlterIndexTogether(
            name='exchangerate',
            index_together={('primary', 'secondary')},
        ),
    ]
